# -*- coding: utf-8 -*-
"""dischargeanalysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17DdOOCYQ1fCPA5HA5S23NyMqsqMSg-kc
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

cpath='../content/Data/Charge/B0005.csv'
dpath='../content/Data/Discharge/B0005.csv'

from google.colab import drive
drive.mount('/content/drive')

import os
import zipfile

zipref=zipfile.ZipFile('../content/drive/My Drive/Data.zip')
zipref.extractall()
zipref.close()

df2=pd.read_csv(dpath)

df2.Date[0]

df2.Date=pd.to_datetime(df2.Date)

df2=df2.set_index('Date')

df2.dtypes

df2.index

df2=df2.drop('Unnamed: 0',axis=1)

df2.head()

sns.set(rc={'figure.figsize':(11,4)})

df2.volatge_battery.plot(linewidth=0.5)

"""OUTLIER at 22-04-2008"""

cols=['current_battery','current_load','temp_battery','time','volatge_battery','volatge_load']
axes=df2['volatge_battery'].plot(marker='.',alpha=1.0,figsize=(11,9),subplots=True)

df2[x='Cycle',y='volatge_load'].plot()

corr=df2.corr()
ax=sns.heatmap(corr,vmin=-1,vmax=1,center=0, cmap=sns.diverging_palette(20, 220, n=200),square=True,annot=True)
ax.set_xticklabels(
    ax.get_xticklabels(),
    rotation=45,
    horizontalalignment='right'
);

"""Heightest correlation feature-: Temp Battery"""

df4=df2.drop('temp_battery',axis=1)

df4.dtypes

"""Correlation Matrix after dropping the highest feature"""

corr=df4.corr()
ax=sns.heatmap(corr,vmin=-1,vmax=1,center=0.5, cmap=sns.diverging_palette(10, 220, n=200),square=True,annot=True)
ax.set_xticklabels(
    ax.get_xticklabels(),
    rotation=45,
    horizontalalignment='right'
);

"""RESAMPLING"""

cols=['current_battery','current_load','temp_battery','time','volatge_battery','volatge_load']

df_mean=df2[cols].resample('10S').mean()

df_mean[df_mean['time']!='NaN']

len(df_mean)

df2.dtypes

"""ANOMALY DETECTION"""

df2.describe()

"""No Anomaly being detected in the discharge phase"""

df2.plot(x='Cycle', y='current_battery', figsize=(12,6))

df2.plot(x='Cycle', y='current_load', figsize=(12,6))

df2.plot(x='Cycle', y='volatge_battery', figsize=(12,6))

df2.plot(x='Cycle', y='volatge_load', figsize=(12,6))

"""But we see a Trend change while plotting the graph for Current_load"""

df3=df2[df2.Cycle<=82]
df4=df2[df2.Cycle>82]
a=df4[df4.current_load<0]

"""We see trend changing from cycle 80 with Current Load becomes positive excpt for Cycle 133 which we take as an anomaly as it goes away from the trend and shows a negative current load"""

fig,ax=plt.subplots(figsize=(10,6))
ax.plot(df4['Cycle'],df4['current_load'], color='blue', label='Current load after cycle 80')
ax.plot(df3['Cycle'],df3['current_load'], color='red', label='Current load Trend before cycle 80')
ax.plot(a['Cycle'],a['current_load'], color='yellow', label='Anomaly')
plt.xlabel('Cycle')
plt.ylabel('Current_load')
plt.legend()
plt.show();

